[package]
name = "cribbage-rs"
version = "0.1.0"
authors = ["Barret Rennie <barret@brennie.ca>"]
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
name = "cribbage"
path = "src/main.rs"

[dependencies]
rand = "0.7.0"
